
const items = [
    { id: 1, name: "Modern Brown Dress for Girls" },
    { id: 2, name: "Men's Leather - Black jacket" },
    { id: 3, name: "Polka Dot Dress for Girls" },
    { id: 4, name: "Stylish White Top for Girls" },
    { id: 5, name: "Men's White T-Shirt with Black Jacket" },
    { id: 6, name: "Essence Mascara Lash Princess" },
    { id: 7, name: "Eyeshadow Palette with Mirror" },
    { id: 8, name: "Powder Canister" },
    { id: 9, name: "Red Lipstick" },
    { id: 10, name: "Red Nail Polish" },
    { id: 11, name: "Calvin Klein CK One" },
    { id: 12, name: "Chanel Coco Noir Eau De" },
    { id: 13, name: "Dior J'adore" },
    { id: 14, name: "Dolce Shine Eau de" },
    { id: 15, name: "Gucci Bloom Eau de" },
    { id: 16, name: "Annibale Colombo Bed" },
    { id: 17, name: "Annibale Colombo Sofa" },
    { id: 18, name: "Bedside Table African Cherry" },
    { id: 19, name: "Knoll Saarinen Executive Conference Chair" },
    { id: 20, name: "Wooden Bathroom Sink With Mirror" },
    { id: 21, name: "Apple" },
    { id: 22, name: "Beef Steak" },
    { id: 23, name: "Cat Food" },
    { id: 24, name: "Chicken Meat" },
    { id: 25, name: "Cooking Oil" },
    { id: 26, name: "Cucumber" },
    { id: 27, name: "Dog Food" },
    { id: 28, name: "Eggs" },
    { id: 29, name: "Fish Steak" },
    { id: 30, name: "Green Bell Pepper" },
    { id: 31, name: "Green Chili Pepper" },
    { id: 32, name: "Honey Jar" },
    { id: 33, name: "Ice Cream" },
    { id: 34, name: "Juice" },
    { id: 35, name: "Kiwi" },
    { id: 36, name: "Black Sun Glasses" },
    { id: 37, name: "Classic Sun Glasses" },
    { id: 38, name: "Green and Black Glasses" },
    { id: 39, name: "Party Glasses" },
    { id: 40, name: "Sunglasses" },
    { id: 41, name: "Blue & Black Check Shirt" },
    { id: 42, name: "Gigabyte Aorus Men Tshirt" },
    { id: 43, name: "Man Plaid Shirt" },
    { id: 44, name: "Man Short Sleeve Shirt" },
    { id: 45, name: "Men Check Shirt" },
    { id: 46, name: "Black Women's Gown" },
    { id: 47, name: "Corset Leather With Skirt" },
    { id: 48, name: "Corset With Black Skirt" },
    { id: 49, name: "Dress Pea" },
    { id: 50, name: "Marni Red & Black Suit" },
    { id: 51, name: "Nike Air Jordan 1 Red And Black" },
    { id: 52, name: "Nike Baseball Cleats" },
    { id: 53, name: "Puma Future Rider Trainers" },
    { id: 54, name: "Sports Sneakers Off White & Red" },
    { id: 55, name: "Sports Sneakers Off White Red" },
    { id: 56, name: "Green Crystal Earring" },
    { id: 57, name: "Green Oval Earring" },
    { id: 58, name: "Tropical Earring" },
    { id: 59, name: "Blue Frock" },
    { id: 60, name: "Girl Summer Dress" },
    { id: 61, name: "Gray Dress" },
    { id: 62, name: "Short Frock" },
    { id: 63, name: "Tartan Dress" },
    { id: 64, name: "IWC Ingenieur Automatic Steel" },
    { id: 65, name: "Rolex Cellini Moonphase" },
    { id: 66, name: "Rolex Datejust Women" },
    { id: 67, name: "Watch Gold for Women" },
    { id: 68, name: "Women's Wrist Watch" },
    { id: 69, name: "Brown Leather Belt Watch" },
    { id: 70, name: "Longines Master Collection" },
    { id: 71, name: "Rolex Cellini Date Black Dial" },
    { id: 72, name: "Rolex Cellini Moonphase" },
    { id: 73, name: "Rolex Datejust" },
    { id: 74, name: "Rolex Submariner Watch" },
    { id: 75, name: "Black & Brown Slipper" },
    { id: 76, name: "Calvin Klein Heel Shoes" },
    { id: 77, name: "Golden Shoes Woman" },
    { id: 78, name: "Pampi Shoes" },
    { id: 79, name: "Red Shoes" },
    { id: 80, name: "Blue Women's Handbag" },
    { id: 81, name: "Heshe Women's Leather Bag" },
    { id: 82, name: "Prada Women Bag" },
    { id: 83, name: "White Faux Leather Backpack" },
    { id: 84, name: "Women Handbag Black" },
    { id: 85, name:"mens-shirts"},
    { id: 86, name:"shirts"}
  ];
  